Repository Kernel360/KDEV4-TRACKY-BE, pull requests merged in 2025-04, with the labels that each got.

#59 EMU - feat #58 시동 off및 주기 정보 화면 개발
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CarOnOffRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CycleGpsRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/config/EnvConfig.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/DriveEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/GpsHistoryEntity.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/ApiResponse.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CarOnOffRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleGpsRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleInfoRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/TokenRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/dto/CarOnOffRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewController.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewSseController.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/dto/CycleLogResponse.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/service/SseService.java
  tracky-emulator/src/main/resources/templates/emulator-start-form.html
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/EnvConfig.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/CarInfoController.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/ApiResponse.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/ApiTokenResponse.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CarOnOffRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CycleGpsRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CycleInfoRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/GpsHistoryMessage.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/TokenRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/config/EnvConfig.java
Labels: Feature

#60 WEB - feat: #33 차량 수정& 차량 삭제 api 추가
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/mapper/CarMapper.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/entity/Member.java
Labels: Feature

#63 WEB - 대여 전체 조회 및 대여 등록
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/RentEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/CarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature

#67 feat #65 Hub 모듈 Cors 설정, 엔티티 수정, RabbitMQ 설정 수정
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CarOnOffRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CycleGpsRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/GpsHistoryRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/RentEntityRepository.java
  tracky-consumer/src/main/resources/application.yml
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/DriveEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/GpsHistoryEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/LocationEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/RentEntity.java
  tracky-core/src/main/resources/application.yml
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CarOnOffRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/WebConfig.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CarOnOffRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CycleGpsRequest.java
  tracky-hub/src/main/resources/application.yml
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentResponse.java
Labels: Feature

#69 HUB - 차량 mdn List 반환 Api
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/TrackyHubApplication.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/infrastructure/repository/CarRepository.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/CarInfoController.java
Labels: Feature

#73 EMU - feat #61 에뮬레이터 여러대 생성개발
  tracky-consumer/Dockerfile
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewController.java
  tracky-emulator/src/main/resources/templates/emulator-start-form.html
Labels: Feature

#74 refactor #65 Hub-Cors URL 추가
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/WebConfig.java
Labels: Refactor

#76 WEB - 렌트 페이지 상세보기 & 검색 & 수정 & 삭제
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/RentEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/ErrorCode.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/RentException.java
  tracky-web/src/main/java/kernel360/trackyweb/member/application/service/MemberService.java
  tracky-web/src/main/java/kernel360/trackyweb/member/domain/model/MemberPrincipal.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/entity/MemberEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/repository/MemberRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtTokenProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/member/presentation/MemberLoginController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/mapper/RentMapper.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentResponse.java
Labels: Feature

#86 WEB - #85 JWT 로그인 관련 설정
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/member/PasswordTest.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/entity/MemberEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtTokenProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/member/presentation/MemberLoginController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/mapper/RentMapper.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentRequest.java
Labels: Feature

#106 WEB - 예약 상태 & 날짜 기준 검색 추가
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature

#104 WEB - 차량 등록 수정 mdn 관련 로직 수정 & 차량 중복 체크 api 추가
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarUpdateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature

#102 차량 검색 -> mdn, 차량 상태, 사용목적 필터링 검색 api 추가
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarUpdateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature

#114 Feat/dashboard car api
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/application/DashboardCarDataService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/domain/CarStatus.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/infrastructure/repository/CarStatusRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/presentation/DashboardController.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtTokenProvider.java
Labels: Feature

#117 WEB - 대시보드 예약현황
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/DashBoardReader.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/RentDashboardDto.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashBoardReaderImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashCarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashRentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
Labels: Feature

#118 WEB - 대시보드 api 최신화
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/CarStatus.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/CarStatusRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/application/DashboardCarDataService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/presentation/DashboardController.java
Labels: Feature

#110 CONSUMER - @Async 주기정보 요청 처리
  tracky-consumer/docker-compose.yml
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/GpsHistoryMessage.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/MessageListener.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/config/AsyncConfig.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/ConsumerController.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/dto/ApiResponse.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/dto/CycleInfoRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQConfig.java
Labels: Feature

#115 WEB - 차량, 렌트 검색 페이지네이션
  tracky-core/src/main/java/kernel360/trackycore/core/common/api/ApiResponse.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/api/PageResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/application/DashboardCarDataService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/domain/CarStatus.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/infrastructure/repository/CarStatusRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/presentation/DashboardController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature

#119 WEB - 차량 이용자 전용 화면 개발
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/config/WebConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/application/ReservationService.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/LocationRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationCarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationDriveRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationRentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/dto/ReservationDrivingsResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/dto/ReservationWithCarResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/rentUserController.java
Labels: Feature

#120 WEB - 통계 관련 api 추가
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/Statistics.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashDriveRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashRentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
Labels: Feature

#123 WEB - 대시보드 Geo 기반 위치 정보 작업
  tracky-web/build.gradle
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/ProvincePolygon.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/components/ProvinceGeometryLoader.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/components/ProvinceMatcher.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/application/DashboardCarDataService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/domain/CarStatus.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/infrastructure/repository/CarStatusRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard2/presentation/DashboardController.java
  tracky-web/src/main/resources/geojson/korea-provinces.geojson
Labels: Feature

#124 Feat/dashboard recent
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/mapper/CarEvent.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarCreateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/emitter/EventEmitterService.java
  tracky-web/src/main/java/kernel360/trackyweb/emitter/EventSseController.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/mapper/RentEvent.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
Labels: Feature

#133 운행 기록 페이지 예약, 차량 별 운행기록 api, 운행기록 별 detail api
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/application/DriveHistoryService.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/CarDriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/DriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/GpsData.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/RentDriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repository/DriveHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repository/GpsHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repository/RentHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/presentation/DriveHistoryApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/presentation/DriveHistoryController.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
Labels: Feature

#142 #WEB - refactor #141 ALB HealthCheck URI 허용
  tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
Labels: Refactor

#147 ALL - hotfix: Dockerfile TimeZone 서울 시간으로 수정
  tracky-consumer/Dockerfile
  tracky-emulator/Dockerfile
  tracky-hub/Dockerfile
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CarOnOffRequest.java
  tracky-web/Dockerfile
Labels: Bug

#145 EMU - 위/경도 생성 수정 및 oTime추가
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/RentException.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CarOnOffRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleGpsRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleInfoRequest.java
Labels: Refactor

#163 WEB - 리팩토링 car 최종..?
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/BizProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/CarProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/DeviceProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/sse/GlobalSseEvent.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/sse/SseEvent.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/BizException.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/CarException.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/DeviceException.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/ErrorCode.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/ExampleNotFoundException.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/GlobalException.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/CarRepository.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/DeviceRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/TrackyWebApplication.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/dto/response/CarDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/dto/response/DeviceResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/DeviceProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repo/CarBizRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDeviceRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/test/java/kernel360/trackyweb/car/application/CarServiceTest.java
Labels: Refactor

#165 EMU - ControlClient(중앙 클라이언트) 추가 및 manager 의존성 수정
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/ControlClient.java
Labels: Refactor

#166 CORE - Emulator VO 수정
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/dto/ApiResponse.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/vo/EmulatorInfo.java
Labels: Refactor

#162 Refactor/member
  tracky-web/src/main/java/kernel360/trackyweb/member/application/MemberService.java
  tracky-web/src/main/java/kernel360/trackyweb/member/application/validation/MemberValidator.java
  tracky-web/src/main/java/kernel360/trackyweb/member/domain/MemberPrincipal.java
  tracky-web/src/main/java/kernel360/trackyweb/member/domain/provider/MemberProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/security/config/SecurityConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/security/filter/JwtAuthenticationFilter.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/security/jwt/JwtTokenProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/security/validation/JwtValidation.java
Labels: Refactor

#167 EMU - core의 GpsInfo Vo 활용 리팩토링
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/vo/EmulatorInfo.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/TrackyEmulatorApplication.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/ControlClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CarOnOffRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleGpsRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleInfoRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/TokenRequest.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
Labels: Refactor

#175 EMU - 에뮬레이터 예외처리 추가
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorException.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorExceptionHandler.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorCode.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorResponse.java
Labels: Refactor

#151 HUB, CONSUMER - RabbitMQ 설정 변경 및 Batch 적용
  tracky-consumer/build.gradle
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/MessageListener.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/config/RabbitMQConfig.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/config/RabbitMQProperties.java
  tracky-consumer/src/main/resources/application.yml
  tracky-core/src/main/resources/application-common.yml
  tracky-core/src/main/resources/application-rabbitmq.yml
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQConfig.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQProperties.java
  tracky-hub/src/main/resources/application.yml
Labels: Feature, Refactor

#180 WEB - car - domain - 최종 refactor
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/CarProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/application/dto/request/CarUpdateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDeviceRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
Labels: Refactor

#179 refactor: Rent Refactoring
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/RentEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/exception/ErrorCode.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/RentProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/sse/SseEvent.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/RentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/response/RentResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/response/RentSseEvent.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repo/CarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/mapper/RentMapper.java
  tracky-web/src/main/java/kernel360/trackyweb/temp/PasswordEncode.java
Labels: Refactor

#169 CONSUMER - Consumer 모듈 리팩토링
  tracky-consumer/build.gradle
  tracky-consumer/src/main/java/kernel360/trackyconsumer/TrackyConsumerApplication.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CarOnOffRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CycleGpsRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/GpsHistoryMessage.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/request/CarOnOffRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/request/CycleGpsRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/request/CycleInfoRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/request/GpsHistoryMessage.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/MessageListener.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/domain/provider/DriveDomainProvider.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/CarEntityRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/DeviceEntityRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/DriveDomainRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/GpsHistoryEntityRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/LocationEntityRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/RentEntityRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/ConsumerController.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/dto/CycleInfoRequest.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/entity/DriveEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/exception/ErrorCode.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/DriveProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/GpsHistoryProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/LocationProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/common/provider/RentProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/DeviceRepository.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/DriveRepository.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/GpsHistoryRepository.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/LocationRepository.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/RentRepository.java
Labels: Refactor

#183 Refactor/sse 위치만 변경
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/common/sse/GlobalSseEvent.java
  tracky-web/src/main/java/kernel360/trackyweb/common/sse/SseEvent.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
Labels: Refactor

#191 feat: 운행기록 차량 list api 생성
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/DriveService.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/response/CarListResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/presentation/DriveController.java
Labels: Feature

#203 query dsl qenitiy 중복 생성 방지 코드 추가 및 Car searchfilter QueryDsl 수정 & pr hook 연동
  .github/workflows/discord-pr-notify.yml
  tracky-core/build.gradle
  tracky-web/src/main/java/kernel360/trackyweb/car/application/dto/request/CarSearchByFilterRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
Labels: Feature

#207 CORE - GpsHistory PK TSID로 변경
  tracky-core/build.gradle
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/GpsHistoryEntity.java
Labels: Refactor

#209 WEB - 운행기록 새로운 시작 및 퀴리 dsl / searchByFilter작업
  .github/workflows/discord-pr-notify.yml
  tracky-core/build.gradle
  tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/DriveProvider.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
  tracky-web/build.gradle
  tracky-web/src/main/java/kernel360/trackyweb/car/application/dto/request/CarSearchByFilterRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
  tracky-web/src/main/java/kernel360/trackyweb/common/config/QuerydslConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/DriveService.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/request/DriveSearchFilterRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/response/DriveHistoryResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/response/DriveListResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/DriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/GpsData.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/GpsHistoryDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/presentation/DriveController.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/application/DriveHistoryService.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/presentation/DriveHistoryController.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
  tracky-web/src/main/resources/application.yml
  tracky-web/src/test/java/kernel360/trackyweb/car/application/CarServiceTest.java
Labels: Feature

#214 refactor: car searchfilter dsl refactoring
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
Labels: Refactor

#215 WEB- Refactor/car sse
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
Labels: Refactor

#230 WEB - Notice 엔티티 생성
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/NoticeEntity.java
Labels: Feature

#242 WEB - Notice 검색 기능 및 페이지네이션 구현
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/NoticeEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/application/NoticeService.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/application/dto/request/NoticeCreateUpdateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/application/dto/request/NoticeSearchByFilterRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/application/dto/response/NoticeDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/application/dto/response/NoticeResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/domain/provider/NoticeProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/infrastructure/repository/NoticeDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/infrastructure/repository/NoticeDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/infrastructure/repository/NoticeDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/notice/presentation/NoticeController.java
  tracky-web/src/main/java/kernel360/trackyweb/sign/infrastructure/security/filter/JwtAuthenticationFilter.java
Labels: Feature

#237 WEB - 실시간 운행중인 차량 하나에 대한 detail api
  tracky-core/src/main/java/kernel360/trackycore/core/common/exception/ErrorCode.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/application/DriveHistoryService.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/CarDriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/RentDriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repo/DriveHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repo/RentHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/presentation/DriveHistoryApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/drivehistory/presentation/DriveHistoryController.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/RealTimeService.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/request/RealTimeCarListRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/response/GpsDataResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/response/RunningCarDetailResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/response/RunningCarResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/presentation/RealTimeController.java
Labels: Feature

#250 WEB - GpsHistory sec 필드 제거 및 oTime에 sec 저장
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/CycleGpsRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/CycleInfoRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/GpsHistoryMessage.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/GpsHistoryEntity.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/request/CycleGpsRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/request/CycleInfoRequest.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/request/GpsHistoryMessage.java
Labels: Refactor

#252 CORE, CUNSUMER - 주기 정보 메시지 역직렬화 문제 해결
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/CycleGpsRequest.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/vo/GpsInfo.java
Labels: Bug, Refactor

#248 WEB - 운행기록 재공사를 위한 api 수정
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/response/CarListResponse.java
Labels: Feature

#245 CONSUMER- TimeDistance 엔티티, SQL 추가 및 저장 기능
  docker-compose.yml
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/domain/provider/TimeDistanceProvider.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/infrastructure/repository/TimeDistanceDomainRepository.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/infrastructure/repository/TimeDistanceDomainRepositoryImpl.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/infrastructure/repository/TimeDistanceRepositoryCustom.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/TimeDistanceEntity.java
  tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/TimeDistanceRepository.java
  tracky-core/src/main/resources/schema.sql
  tracky-web/build.gradle
Labels: Feature

#262 운행기록 검색 api -> 고도화 진행 예정
  tracky-core/src/main/resources/application-common.yml
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/DriveService.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/request/DriveListRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/DriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/GpsData.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/presentation/DriveController.java
Labels: Feature

#267 CORE, CONSUMER - 차량 마지막 운행 시간 필드 추가
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/CarEntity.java
  tracky-core/src/main/resources/schema.sql
Labels: Feature

#264 WEB - 페이징 필터 softdelete 등
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/RentEntity.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentCreateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentSearchByFilterRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentUpdateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/util/UuidGenerator.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
Labels: Feature, Refactor

#269 CONSUMER - GPS 오류 데이터 제외
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/DriveEntity.java
  tracky-core/src/main/resources/schema.sql
Labels: Feature

#276 feat: rent address setting
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentCreateRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/util/UuidGenerator.java
Labels: Feature

#277 HUB - 실시간 경로 추적 Queue 추가
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-core/src/main/resources/application-rabbitmq.yml
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQConfig.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQProperties.java
  tracky-hub/src/main/resources/application.yml
Labels: Feature

#280 WEB - 실시간 추적용 web-queue 추가
  tracky-web/build.gradle
  tracky-web/src/main/java/kernel360/trackyweb/common/config/RabbitMQConfig.java
  tracky-web/src/main/java/kernel360/trackyweb/common/config/RabbitMQProperties.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/request/CycleGpsRequest.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/dto/request/GpsHistoryMessage.java
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/service/MessageListener.java
  tracky-web/src/main/resources/application.yml
Labels: Feature

#285 dashboard 미반납현황 && dashboard refactoring -> 추후 query dsl 필요
  tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/CarProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardReader.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/RentDashboardDto.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/ReturnResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/impl/DashBoardReaderImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/provider/DashGpsHistoryProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/repo/CarStatusRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/repo/DashCarRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/repo/DashDriveRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/repo/DashRentRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustomImpl.java
Labels: Feature

#286 CORE - ALB HealthCheck 허용
  tracky-core/src/main/resources/application-common.yml
Labels: Bug, Refactor

#288 WEB - WebQueue -> WEB -> SSE
  tracky-web/src/main/java/kernel360/trackyweb/realtime/application/service/MessageListener.java
Labels: Feature

#284 EMU - 에뮬레이터 생성 과정 수정
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/ControlClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/response/MdnBizResponse.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewController.java
  tracky-emulator/src/main/resources/application.yml
  tracky-emulator/src/main/resources/templates/emulator-start-form.html
Labels: Feature
