Repository Kernel360/KDEV4-TRACKY-BE, pull requests merged in 2025-05, with the labels that each got.

#299 Feat: core-statistic provider 추가
  tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/DailyStatisticProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/MonthlyStatisticProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/TimeDistanceProvider.java
Labels: Feature

#291 CONSUMER - 시동 on/off시 차량 상태 변경
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/CarEntity.java
Labels: Feature

#313 WEB - MdnStatus 누락 과 서버 에러 사항 수정
  tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/MdnStatus.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustomImpl.java
Labels: Feature

#303 CORE, CONSUMER - TimeDistance seconds 필드 추가
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/domain/provider/TimeDistanceDomainProvider.java
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/TimeDistanceEntity.java
Labels: Feature

#325 feat: 메인 대시보드 월별 통계 api 생성
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/Statistics.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/Statistics.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/application/DriveService.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/vo/DriveHistory.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/domain/vo/GpsData.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/drive/presentation/DriveController.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/domain/provider/DailyStatisticProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/domain/provider/MonthlyStatisticProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/daily/DailyStatisticRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/daily/DailyStatisticRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/monthly/MonthlyStatisticDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/monthly/MonthlyStatisticRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/monthly/MonthlyStatisticRepositoryCustomImpl.java
Labels: Feature

#328 HUB, CONSUMER - hotfix 주기정보 dto 수정
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/CycleInfoRequest.java
  tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/GpsHistoryMessage.java
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/hub/application/dto/request/GpsHistoryMessage.java
Labels: Bug

#329 Fix : dashboard statistic
  tracky-emulator/src/main/resources/application.yml
  tracky-hub/src/main/java/kernel360trackybe/trackyhub/car/infrastructor/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/daily/DailyStatisticRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/monthly/MonthlyStatisticDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/infrastructure/repository/monthly/MonthlyStatisticDomainRepositoryImpl.java
Labels: Bug

#332 fix : 운행 기록 리스트 디버깅
  tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
Labels: Bug

#336 fix : 업체 대시보드 차량 현황 API 수정 및 QueryDsl전환
  tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepository.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/DashboardCarStatusResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/DashboardRentStatusResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/DashboardReturnResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/dto/response/DashboardStatisticsResponse.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/CarStatusTemp.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/vo/ProvincePolygon.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/components/ProvinceGeometryLoader.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/components/ProvinceMatcher.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
Labels: Refactor

#341 대시보드 차량 위치 지도 API querydsl 전환
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepositoryCustom.java
  tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepositoryCustomImpl.java
Labels: Refactor

#344 Hot Fix : 월별 스케줄러 디버깅
  tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/MonthlyStatisticEntity.java
  tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
  tracky-web/src/main/java/kernel360/trackyweb/statistic/domain/provider/MonthlyStatisticProvider.java
Labels: Bug
